# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7a526770a7ee1c760737780769d5880d"
name = "regional-partnership-app"
handle = "regional-partnership-app-13"
application_url = "https://recept-app.onrender.com"
embedded = true
dev_store = "1tmiwd-test.myshopify.com"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://recept-app.onrender.com/auth/callback",
  "https://recept-app.onrender.com/auth/shopify/callback",
  "https://recept-app.onrender.com/api/auth/callback"
]

[pos]
embedded = false
